#!/bin/sh

# Fix Gnome Apps Slow Start due to failing services
# Add this when you include flatpak in your system
#dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

[ -f ~/.local/bin/remaps ] && remaps &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources &	# Xresources colors/settings on startup
xwallpaper --zoom ~/.local/share/wallpaper
xcompmgr &		# xcompmgr for transparency
xset r rate 300 50 &	# Speed xrate up
unclutter --timeout=0 --ignore-scrolling &		# Remove mouse when idle
