#!/bin/sh

[ -f ~/.local/bin/remaps ] && remaps &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources &
xcompmgr &		# xcompmgr for transparency
xset r rate 300 50 &	# Speed xrate up
unclutter --timeout=1 --ignore-scrolling &
xwallpaper --zoom ~/.local/share/wallpaper &
connectspeakers
