[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
source ~/.config/nvim/settings/startify.vimrc
'''

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'psliwka/vim-smoothie'
