[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'psliwka/vim-smoothie'

# [[plugins]]
# repo = 'machakann/vim-sandwich'
# hook_source = '''
#   let g:sandwich_no_default_key_mappings = 1

#   nmap [Space]sa <Plug>(operator-sandwich-add)
#   nmap [Space]sd <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
#   nmap [Space]sr <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
#   nmap [Space]sdb <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
#   nmap [Space]srb <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)

#   xmap sa <Plug>(operator-sandwich-add)
#   omap sa <Plug>(operator-sandwich-g@)
#   xmap sd <Plug>(operator-sandwich-delete)
#   xmap sr <Plug>(operator-sandwich-replace)

#   omap ib <Plug>(textobj-sandwich-auto-i)
#   xmap ib <Plug>(textobj-sandwich-auto-i)
#   omap ab <Plug>(textobj-sandwich-auto-a)
#   xmap ab <Plug>(textobj-sandwich-auto-a)
#   omap is <Plug>(textobj-sandwich-query-i)
#   xmap is <Plug>(textobj-sandwich-query-i)
#   omap as <Plug>(textobj-sandwich-query-a)
#   xmap as <Plug>(textobj-sandwich-query-a)
# '''

