[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
